apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "boot-test"
  description: "test"
  annotations:
    github.com/project-slug: dbbaskette/boot-test
    backstage.io/techdocs-ref: url:https://github.com/dbbaskette/boot-test
spec:
  type: service
  lifecycle: experimental
  owner: "dbbaskette"
